/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Loïc Norgeot (https://sketchfab.com/norgeotloic)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/our-corner-of-universe-37476c8aaba148fbaf4b6c3664545995
title: Our corner of universe
*/

import React, { useLayoutEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import * as THREE from "three";
import { starsAnimation } from "@/animations/animations";
import { useGSAP } from "@gsap/react";

export function Stars() {
  const ref = useRef<any>();
  const { camera, mouse } = useThree();
  const vec = new THREE.Vector3();
  const { nodes, materials, scene } = useGLTF(
    "/assets/models/stars/stars.gltf"
  );

  useGSAP(() => {
    starsAnimation(ref?.current);
  });

  useFrame(() =>
    camera.position.lerp(
      vec.set(mouse.x * 2, mouse.y * 1, camera.position.z),
      0.02
    )
  );
  return (
    <group dispose={null} scale={20} position={[0, -10, 0]} ref={ref}>
      <directionalLight color='yellow' intensity={20} position={[0, 0, 5]} />
      {/* <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Earth_0.geometry} material={materials.earth} />
        <group
          position={[-7.65, -2.72, -2.69]}
          rotation={[1.33, -0.43, -1.88]}
          scale={0.63}
        >
          <mesh
            geometry={nodes.Plane8968_0.geometry}
            material={materials.Material}
          />
        </group>
      </group> */}
      <primitive object={scene} dispose={null} />
    </group>
  );
}

useGLTF.preload("/assets/models/stars/stars.gltf");
