/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: arthur (https://sketchfab.com/Arthur_mf)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/ethereum-ac40cebf61464c548776a0c20b47ccc7
title: Ethereum
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Coin() {
  const { nodes, materials }: any = useGLTF("/assets/models/coin/coin.gltf");

  return (
    <group dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[-0.22, 0, -0.38]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={2.41}
          >
            <mesh
              geometry={nodes.Object_4.geometry}
              material={materials["Material.004"]}
            />
          </group>
          <group
            position={[-0.22, 0, -0.38]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={2.41}
          >
            <mesh
              geometry={nodes.Object_6.geometry}
              material={materials["Material.005"]}
            />
          </group>

          <group
            position={[-0.22, 0, -0.38]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={2.41}
          >
            <mesh
              geometry={nodes.Object_14.geometry}
              material={materials["Material.001"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/assets/models/coin/coin.gltf");
