"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThirdwebProvider, useAddress } from "@thirdweb-dev/react";
import StyledComponentsRegistry from "./registry";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const activeChain = "optimism-goerli";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  useEffect(() => {
    document.title = "Cosmos | Descentralized invoices | by Alejo Avenali";
    let link: any = document.querySelector("link[rel~='icon']");
    if (!link) {
      link = document.createElement("link");
      link.rel = "icon";
      document.getElementsByTagName("head")[0].appendChild(link);
    }
    link.href = "/assets/images/favicon.svg";
  }, []);

  return (
    <StyledComponentsRegistry>
      <ThirdwebProvider
        clientId={process.env.NEXT_PUBLIC_TEMPLATE_CLIENT_ID}
        activeChain={activeChain}
      >
        <html lang='en'>
          <body className={inter.className}>{children}</body>
        </html>
      </ThirdwebProvider>
    </StyledComponentsRegistry>
  );
}
